### ISSUE TITLE
场景图等数据链接失效

### ISSUE THREAD

**Issue by YuyingShang** [UMass-Foundation-Model/VisualCoT#1]
场景图等数据链接失效，请问可以重新上传对应数据吗？谢谢
![image](https://github.com/UMass-Foundation-Model/VisualCoT/assets/53067922/10a0df46-d437-4c5e-b691-84054b990426)

**Comment by zhouqqhh** [comment]
Hi,
Sorry for the late reply. We will upload the files to a new place soon.

**Comment by zhouqqhh** [comment]
Hi,
We have just updated the urls.
